### PR TITLE
Fixes for cmake

### PR DESCRIPTION
**Pull request by mtaillefumier**
- C and C standards
- install cp2k.pc file

### CODE REVIEW

**Comment by haampie** [comment]
@mtaillefumier still running into some issue:

```
CMake Error at /spack/opt/spack/linux-sles15-zen2/gcc-13.2.0/cp2k-2023.2-33eadaiwwdnpno2pzo5kt3uhmbh4inyl/lib64/cmake/cp2k/cp2kConfig.cmake:29 (find_package):
  By not providing "FindLapack.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Lapack", but
  CMake did not find one.
```

I guess the cmake config file should temporarily (?) add the relevant path to CMAKE_MODULE_PATH

**Comment by mtaillefumier** [comment]
I am probably putting the findLapack.cmake etc... in the wrong directory. I checked on my local install and they are there
`
/opt/spack/linux-fedora38-cascadelake/gcc-13.2.1/cp2k-master-yrktnpvb6bwh3zsguhdurjeval3yxgzc/lib64/cmake/cp2k/cmake` I should move them one directory down I think. That's why I want the cmake build system as default.

**Comment by mtaillefumier** [comment]
in your case the findLapack etc... are all in `/spack/opt/spack/linux-sles15-zen2/gcc-13.2.0/cp2k-2023.2-33eadaiwwdnpno2pzo5kt3uhmbh4inyl/lib64/cmake/cp2k/cmake`

**Comment by mtaillefumier** [comment]
one more fix

**Comment by haampie** [comment]
Also there are some references to SIRIUS instead of CP2K ;p while you're at it

**Comment by mtaillefumier** [comment]
thanks I will fix those as well.

**Comment by mtaillefumier** [comment]
@haampie : Normally all issues should be fixed, til the next one ;p

**Comment by haampie** [comment]
Will try soon ™️

**Pull request merged**
